# Generated by Django 6.0.4 on 2026-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careitem',
            name='recurrence_notes',
        ),
        migrations.AddField(
            model_name='careitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='careitem',
            name='recurrence_dates',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='careitem',
            name='recurrence_mode',
            field=models.CharField(choices=[('none', 'No recurrence'), ('daily', 'Daily'), ('selected_weekdays', 'Selected weekdays'), ('weekly', 'Weekly'), ('monthly_dates', 'Monthly dates'), ('specific_dates', 'Specific dates')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='careitem',
            name='recurrence_weekdays',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='careitem',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careitem',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
