# Generated by Django 6.0.4 on 2026-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('user', 'User ended'), ('idle', 'Idle timeout'), ('tab_close', 'Tab/browser close'), ('context_change', 'Patient/context changed')], max_length=30),
        ),
    ]
