# Generated by Django 6.0.4 on 2026-04-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_routine_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='intolerances',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PatientDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_image', 'AI Image Analysis')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_entries', to='patients.patient')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'name'), name='uq_patient_disease_name')],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_image', 'AI Image Analysis')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_entries', to='patients.patient')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'name', 'dosage'), name='uq_patient_medication_name_dosage')],
            },
        ),
        migrations.CreateModel(
            name='PatientSensitivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('allergy', 'Allergy'), ('intolerance', 'Intolerance')], max_length=20)),
                ('severity', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_image', 'AI Image Analysis')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_entries', to='patients.patient')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'kind', 'name'), name='uq_patient_sensitivity_kind_name')],
            },
        ),
    ]
